jobs:
  build:
    steps:
      - script: |
          set -e
          . $HOME/.cargo/env

          cd uci
          cargo install --path uci
  restart:
    needs: ['build']
    steps:
      - script: |
          set -e

          echo "Restarting service. Losing runtime info..."
          systemctl --user restart ucid
links:
  'uci': ${project.repos.uci.path}

integrations:
  gitlab:
    token: ${project.secrets.gitlab_token}
    project_id: '42995967'
    rev: ${project.repos.uci.rev}
