jobs:
  build:
    script: |
      set -e
      . $HOME/.cargo/env

      cd uci
      cargo install --path uci
  restart:
    needs: ['build']
    script: |
      set -e

      function restart() {
        sleep 10
        systemctl --user restart ucid
      }

      export -f restart

      echo "Restarting service in 10 seconds..."
      restart 1>&- 2>&- &disown
links:
  'uci': ${project.repos.uci.path}

integrations:
  gitlab:
    token: ${project.secrets.gitlab_token}
    project_id: '42995967'
    rev: ${project.repos.uci.rev}

  telegram:
    token: ${project.secrets.tg_token}
    chat_id: ${project.secrets.tg_chat_id}
    pipeline_id: ${pipeline.id}
    topic_id: ${project.secrets.tg_topic_id}
