jobs:
  build-docker-image:
    type: build
    image: uci-web-gui-build
    path: ${project.repos.uci.path}/webgui

  _make-dist-dir:
    type: script
    env:
      DATA_DIR: ${project.data.path}/webgui
      DIST_DIR: ${project.repos.uci.path}/webgui/dist
    script: |
      set -e

      mkdir -p ${DATA_DIR} || echo "Already exists"

  build:
    needs:
      - build-docker-image
      - _make-dist-dir

    type: script
    image: uci-web-gui-build
    volumes:
      '/build': ${project.repos.uci.path}
      '/dist': ${project.data.path}/webgui
      '/target': webgui-target-cache
    env:
      UCI_BASE_URL: 'https://uci.ilyay.space/api'
      UCI_WS_BASE_URL: 'wss://uci.ilyay.space/api'
      CARGO_TARGET_DIR: '/target'
    script: |
      set -e

      . /root/.cargo/env

      cd webgui
      /trunk build -d /dist

integrations:
  github:
    token: ${project.secrets.github_token}
    repo: 'iliayar/uci'
    rev: ${project.repos.uci.rev}
    ui_url: 'https://uci.ilyay.space'
    jobs_to_report:
      - build
