jobs:
  # build-docker-image:
  #   do:
  #     type: build
  #     image: uci-web-gui-build
  #     path: ${project.repos.uci.path}/webgui

  _make-dist-dir:
    do:
      type: script
      env:
        DATA_DIR: ${project.data_path}/webgui
      script: |
        set -e
  
        mkdir -p ${DATA_DIR} || echo "Already exists"

  build:
    needs:
      - build-docker-image
      - _make-dist-dir

    do:
      type: script
      env:
        UCI_BASE_URL: 'https://uci.iliay.ar/api'
        UCI_WS_BASE_URL: 'wss://uci.iliay.ar/api'
        CARGO_TARGET_DIR: ${project.data_path}/webgui-cache
        SRC_DIR: ${project.repos.uci.path}
        DIST_DIR: ${project.data_path}/webgui
      script: |
        set -e
        . /etc/profile.d/nix.sh

        cd ${SRC_DIR}/webgui

        nix develop -c trunk build -d ${DIST_DIR}

integrations:
  github:
    token: ${project.secrets.github_token}
    repo: 'iliayar/uci'
    rev: ${project.repos.uci.rev}
    ui_url: 'https://uci.iliay.ar'
    jobs_to_report:
      - build
