bind9:
  zones:
    'ilyay.space':
      cnames:
        - 'uci'
caddy:
  hostnames:
    'uci.ilyay.space': |
      handle /api/* {
          uri strip_prefix /api
          reverse_proxy :3002
      }

      handle * {
          root * ${project.data.path}/webgui
          try_files {path} /index.html
          file_server
      }
