[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.14.0"
log = "0.4.17"
logger = "0.4.0"
pretty_env_logger = "0.4.0"
tokio = { version = "1.24.2", features = ["macros", "rt", "rt-multi-thread"] }
warp = "0.3.3"
