jobs:
  run_script:
    steps:
      - type: script
        image: ubuntu
        env:
          TEST_ENV: aboba
        script: |
          apt-get update && apt-get install -y curl

          pwd
          ls -la
          ls src
          echo "KEK: $(id)" >> out/echo
          echo "AMOGUS" >> /mnt/test/file
          echo $TEST_ENV >> /mnt/test-global/file
          curl common-service/AMOGUS >> out/file
        volumes:
          '/mnt/test': test-vol
          '/mnt/test-global': global-test-vol
        networks:
          - test-global-net
links:
  'src': ${project.repos.test.path}
  'out': ${project.data_path}/some_result
